apiVersion: apps/v1
kind: Deployment
metadata:
  name: supermariogame-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supermariogame
  template:
    metadata:
      labels:
        app: supermariogame
    spec:
      automountServiceAccountToken: false
      containers:
      - image: vani0909/supermariogitopsproject:2
        name: supermariogame-container
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "100m"
            memory: "128Mi"
            ephemeral-storage: "500Mi"
          limits:
            cpu: "250m"
            memory: "256Mi"
            ephemeral-storage: "1Gi"
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000

---
apiVersion: v1
kind: Service
metadata:
  name: supermariogame-service
spec:
  selector:
    app: supermariogame
  ports:
  - protocol: TCP
    port: 8600  # <-- Change this line to your desired port
    targetPort: 8080
  type: LoadBalancer